#!/bin/bash
#
# Builds a Docker or Vagrant container running Fedora 21.
#
set -e
build_box=radiasoft/sirepo
build_base_docker=radiasoft/beamsim
build_base_vagrant=$build_base_docker

. "$(dirname "$0")"/../../../radiasoft/fedora-container/libexec/build.sh
