#!/bin/bash
#
# Builds a Docker or Vagrant container running Fedora 21.
#
set -e
build_box=radiasoft/beamsim
build_base_docker=radiasoft/fedora21
build_base_vagrant=radiasoft/fedora21

. "$(dirname "$0")"/../../../radiasoft/fedora-container/libexec/build.sh
