#!/bin/bash
. ~/.pyenv/pyenv.d/exec/radia-synergia2dir.bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

#
# Fixups for Bivio environment running in terminado.
#
# We don't want PROMPT_COMMAND for anything
unset PROMPT_COMMAND
if [[ -n $PS1 ]]; then
    export PS1='\W$ '
    export TERM=xterm
fi

if [[ -f ~/'{notebook_bashrc}' ]]; then
    . ~/'{notebook_bashrc}'
fi
