#!/bin/bash

d=$(dirname "$(dirname "$(python -c 'import sys; sys.stdout.write(sys.executable)')")")/lib
export SYNERGIA2DIR=$d
export LD_LIBRARY_PATH=$d:/usr/lib64/openmpi/lib
export PYTHONPATH=$d

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

#
# Fixups for Bivio environment running in terminado.
#
# We don't want PROMPT_COMMAND for anything
unset PROMPT_COMMAND
if [[ -n $PS1 ]]; then
    export PS1='\W$ '
    export TERM=xterm
fi

if [[ -f ~/'{notebook_bashrc}' ]]; then
    . ~/'{notebook_bashrc}'
fi
