#!/bin/bash
#
# Builds a Docker or Vagrant container running Fedora 21.
#
build_box=radiasoft/fedora
build_base_docker=fedora:21
build_base_vagrant=hansode/fedora-21-server-x86_64

. ../fedora-container/libexec/build.sh
