# ipython notebook for default
# Generated by /home/vagrant/src/radiasoft/pykern/pykern/pykern_cli/ipython_service.py on Mon Oct 26 21:13:05 2015
c = get_config()
c.IPKernelApp.pylab = None
c.NotebookApp.base_kernel_url = '/'
c.NotebookApp.base_url = '/'
c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.open_browser = False
c.NotebookApp.port = 8000
